## -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

import ns3waf
import os

def configure(conf):
    ns3waf.check_modules(conf, ['core', 'internet', 'point-to-point', 'netanim'], mandatory = True)

def build(bld):
    bld(name = "build dce_example", color = "YELLOW", always = True,
            cwd = bld.path.abspath(), rule = "gcc -O3 -Wall -fPIC -D_GNU_SOURCE -o dce_example example_program.c -lpthread -pie -rdynamic")

    bld.build_a_script('dce', needed = ['core', 'internet', 'dce', 'point-to-point' ], target='bin/dce_example', source=['dce_example.cc'])
